### ISSUE TITLE
processed data problem 

### ISSUE THREAD

**Issue by lovelyhan** [didi/hetsann#6]
Dear authors, thanks for your insightful research and the released codes.
I have met an error when i use the provided Aminer dataset.
I have installed packages required in the requirements, and also ensure the CUDA's and the cuDNN's version requirements.
The error information is as follows:

`Traceback (most recent call last):
  File "execute_sparse.py", line 138, in <module>
    train_mask, val_mask, test_mask = process.load_heterogeneous_data(dataset, train_rate=train_rate, target_node=target_node)
  File "/home/user/hetsann/HetSANN_M/utils/process.py", line 200, in load_heterogeneous_data
    adj, adj_type, features, labels = dataset_dict[dataset_str](target_node=target_node)
  File "/home/user/hetsann/HetSANN_M/utils/process.py", line 170, in load_aminer
    data = sio.loadmat(dataset)
  File "/home/user/anaconda3/envs/py3.5/lib/python3.5/site-packages/scipy/io/matlab/mio.py", line 141, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/home/user/anaconda3/envs/py3.5/lib/python3.5/site-packages/scipy/io/matlab/mio.py", line 65, in mat_reader_factory
    mjv, mnv = get_matfile_version(byte_stream)
  File "/home/user/anaconda3/envs/py3.5/lib/python3.5/site-packages/scipy/io/matlab/miobase.py", line 241, in get_matfile_version
    raise ValueError('Unknown mat file type, version %s, %s' % ret)
ValueError: Unknown mat file type, version 52, 56`

Is there any hints for this error?
Thanks a lot.

**Comment by NovelinUp** [comment]
Hi, have you done with this problem? @lovelyhan
